# Generated by Django 3.0.7 on 2020-06-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='slug', unique=True, verbose_name='SLUG'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='list_posts',
        ),
    ]
